### PR TITLE
[TASK] Avoid TSFE->page in Data chapter

### PR DESCRIPTION
**Pull request by brotkrueml**
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1074
Releases: main, 13.4

### CODE REVIEW

**Comment by linawolf** [comment]
Please rebase onto main to resolve warnings

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
Please check if a backport is needed and if so make a manual backport

**Comment by brotkrueml** [comment]
@linawolf If you want to avoid outdated information in the current LTS manual, feel free to provide a backport, IMHO this is the task of the merger. If you think this is not necessary, please ignore my comment.

**Comment by brotkrueml** [comment]
Also removed obviously wrong "backport-done" label (and the other as it is now misleading).

**Pull request merged**
