### PR TITLE
Update Index.rst

### PR DESCRIPTION
**Pull request by misterboe**

### CODE REVIEW

**Comment by marble** [comment]
Hello misterboe, thanks for your contribution. Are you sure? I haven't used this so I don't know. Can you write a sentence about the change? Since when, since which version? Would be good we don't introduce something doubtful.

**Comment by misterboe** [comment]
Hi, i just startet a new 7.4 install and searched for rendering the new backend layouts: 

```
mod.web_layout.BackendLayouts {
    home {
        title = home
        name = home
        icon = EXT:fred/Resources/Public/Images/BackendLayouts/home.png
        config {
            backend_layout {
                colCount = 1
                rowCount = 2
                rows {
                    1 {
                        columns {
                            1 {
                                name = Main
                                colPos = 0
                                colspan = 1
                            }
                        }
                    }
                }
            }
        }
    }
}
```

when i want to render the home Template my setup had to look like this: 

```
## PAGE
page = PAGE
page.10 = FLUIDTEMPLATE
page.10 {

    templateName = TEXT
    templateName.stdWrap {
        cObject = TEXT
        cObject {
            data = levelfield:-2,backend_layout_next_level,slide
            override.field = backend_layout
            split {
                token = pagets__
                1.current = 1
                1.wrap = |
            }
        }
        ifEmpty = Default
    }
    layoutRootPaths {
        10 = EXT:myext/Resources/Private/Layouts
    }
    partialRootPaths {
        10 = EXT:myext/Resources/Private/Partials
    }
    templateRootPaths {
        10 = EXT:myext/Resources/Private/Templates
    }
}
```

if i use this configuration i can place a `home.html` in `EXT:myext/Resources/Private/Templates` and it's shown in FE

All other ways i found gave me 'Oops, an error occurred!'

**Comment by marble** [comment]
Let's first find out about the details of this issue before we finally make the change. Cool you raised it.

**Comment by marble** [comment]
Hi, I'm closing this issue for now. If it is still valid: Can you send an uptodate pull request? Thank you.

**Comment by misterboe** [comment]
i dont know why you cloed this RP, have you checked if the version of the dokumentation is working?

**Comment by marble** [comment]
Sorry, seems like a mistake of mine. Shouldn't be closed. ("übereifrig" ...)

**Comment by Chrissitopher** [comment]
What does the content, which page.10.templateName.stdWrap.cObject.data returns, look like?

**Comment by marble** [comment]
This ticket has been open for a long time and I admit that it would be nice to have the correct answer and add it to the documentation. But I'm kindly asking everybody to understand that the documentation team is veeeerrry small and cannot do all kinds of code-checks. This should be done with a suitable forge ticket first. Once we have a definite answer we can add it to documention. To get the ticket out of my daily view I'm closing it now.

**Pull request closed without merging**
