### PR TITLE
[TASK] Make the AbstractPlugin @internal

### PR DESCRIPTION
**Pull request by linawolf**
references: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/171
releases: main

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Please shed light on me: Why remove instantly `_LOCAL_LANG` but not `_DEFAULT_PI_VARS`.

I am with you to remove both properties from documentation, but when `_DEFAULT_PI_VARS` is removed from Core, the AbstractPlugin may not working anymore. Or do I miss something?

**Comment by linawolf** [comment]
`_LOCAL_LANG` was moved to the Extbase-only section, it can still be used. `_DEFAULT_PI_VARS` has to be removed all together

**Comment by brotkrueml** [comment]
`_DEFAULT_PI_VARS` has to be removed all together

Then let's remove it from docs now, as AbstractPlugin is internal now (and the documentation for it is hidden).

**Comment by linawolf** [comment]
I am working on the follow up Core change right now.

**Review by brotkrueml — APPROVED** [review]

**Pull request merged**
