### PR TITLE
Adopt menu processor example to Bootstrap 5

### PR DESCRIPTION
**Pull request by froemken**
* Use data-bs-toggle instead of data-toggle
* Remove aria-expanded. It is not used in the bootstrap examples anymore
* Remove a white space
* Use hasSubpages instead of counting the children
* Add missing data to access the page UID of subpages

### CODE REVIEW

**Review by linawolf — CHANGES_REQUESTED** [review]
Please make the changes to EXT:examples then regenerate this file

**Comment by froemken** [comment]
I have created a patch for the examples extension:
https://github.com/TYPO3-Documentation/t3docs-examples/pull/182

But don't know how to "re-generate" the file...

**Comment by linawolf** [comment]
@froemken I am sorry, we have neglected to document how to generate code-snippets. Working on the documentation right now.

I have made a PR https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/739 with the generated code snippets. Once that PR is merged you can rebase this one and then we are good to go

**Comment by froemken** [comment]
There is no need to change something anymore

**Pull request closed without merging**
