### PR TITLE
[TASK] Improve stdWrap.formattedDate

### PR DESCRIPTION
**Pull request by brotkrueml**
An example for a custom date/time format derived from a timestamp has been added as a showcase.

Additionally, add a heading for each example to improve readability.

Releases: main, 12.4

### CODE REVIEW

**Review by froemken — APPROVED** [review]
Thank you for your patch.

Some marks:
Normally we have 2 whitespaces indent for TypoScript, but as all other examples in that file have 4 whitespaces, it's OK for me.

I have tested your snippet. For me it's `2023-03-17T04:00:00+0100`. Seems you're living at greenwich timezone ;-)

**Comment by brotkrueml** [comment]
My ddev is set up with UTC.

**Comment by brotkrueml** [comment]
About the indentation: I adopted the indents from the example above.

**Comment by linawolf** [comment]
@froemken I just noticed, that the .editorconfig is incomplete.

Introducing a propper .editorconfig would therefore be a follow up.

**Review by linawolf — APPROVED** [review]

**Pull request merged**
