### PR TITLE
[TASK] Add note to avoid loginUser and usergroup conditions

### PR DESCRIPTION
**Pull request by brotkrueml**
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/434
Releases: 11.5

### CODE REVIEW

**Comment by lolli42** [comment]
this will be handled by my bigger condition-refactoring patch in this area. maybe wait for its merge, then have a look at it again.

**Comment by brotkrueml** [comment]
> this will be handled by my bigger condition-refactoring patch in this area. maybe wait for its merge, then have a look at it again.

So another patch will adjust the docs again. Okay, will wait ;-)

**Comment by lolli42** [comment]
i think it's done and merged now in main. unsure if you still want something for v11.

**Comment by brotkrueml** [comment]
> i think it's done and merged now in main. unsure if you still want something for v11.

It is only a hint for v11 users that they should use the frontend.user and backend.user conditions instead of the in v12 deprecated ones to stay forward-compatible. So they avoid additional work when upgrading.

So, yes, only v11 for this patch. v12 is another patch:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/719

**Review by linawolf — APPROVED** [review]

**Pull request merged**
