### PR TITLE
use [END] in upper case letters

### PR DESCRIPTION
**Pull request by franzholz**

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Reason?

**Comment by franzholz** [comment]
Please: All examples should be equal.

**Comment by linawolf** [comment]
The Core is predominantely using `[END]` in upper Case, however `[GLOBAL]` is much more common. I would opt for changing them all to upper case.

**Review by linawolf — CHANGES_REQUESTED** [review]
Let us change all examples to upper case `[END]` as the Core does

**Review by brotkrueml — APPROVED** [review]

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
@franzholz thanks for catching this!

**Pull request merged**
