### PR TITLE
Update Index.rst

### PR DESCRIPTION
**Pull request by blueamerican**
remove wrong Anführungszeichen

### CODE REVIEW

**Comment by tomwarwick** [comment]
Hi Markus, have you tested this? I believe the quotation marks are required.

**Comment by blueamerican** [comment]
@tomwarwick 

Yes, i testet it. The qotation marks are right on the right side, not on the left.

**Comment by brotkrueml** [comment]
This change does not fit to the paragraph above: "If constant is a string put constant in quotes:" Both cases are handled for now in the docs: Is value an integer, use no quotes, is value a string, use quotes for both sides.
Will investigate. If applicable, has also be changed in 11.5 and main.

**Comment by blueamerican** [comment]
Quotations on the left side do not work in V10 nor in V11. I tested it.

**Comment by brotkrueml** [comment]
Okay, I testet the following in v10 and v11:

Constants in root template:
```
foo.bar = 4711
```
Conditions in setup in root template:
```
[{$foo.bar} == 4711]
["{$foo.bar}" == 4711]
[{$foo.bar} == "4711"]
["{$foo.bar}" == "4711"]
```

Every condition works correctly. @blueamerican : **So, can you give us your use case, where this does not work?**

But I agree: The differentiation between integer and string is not necessary.

**Comment by blueamerican** [comment]
ah, ist was my mistake.

My constant was
foo = "bar"

As a result, this does not work:

["{$foo}" == "bar"]

Interestingly, then this works:

[{$foo} == "bar"]

But anyway, your're right.. sorry for the confusion.

**Pull request closed without merging**
