### PR TITLE
add notice about addQueryString

### PR DESCRIPTION
**Pull request by macjohnny**

### CODE REVIEW

**Comment by macjohnny** [comment]
plase backport it to 7.6, 6.2

**Comment by liayn** [comment]
@macjohnny This PR hasn't been merged, right? So why backport?

**Comment by marble** [comment]
He/we decided later to better close the issue. At that time the backport request was already there. Can be ignored.

**Comment by macjohnny** [comment]
it does not seem this issue will ever be fixed, so at least it should be documented

**Comment by marble** [comment]
I've changed the text a bit. Ok?

**Comment by macjohnny** [comment]
@marble ok. maybe we should even add the word "cache poisoning"? it can be a serious issue...

**Comment by marble** [comment]
What would be a possible sentence?

**Comment by marble** [comment]
BTW, I just reworked ("reSTified") that page. Should soon be rendered and appear.

**Comment by macjohnny** [comment]
@marble how about "This would be a security issue of type cache poisoning."?

**Comment by marble** [comment]
It is updated now: "Additionally the security risk of cache poisoning has to be considered."
That can't be wrong, I think.

**Comment by macjohnny** [comment]
@marble great, thanks! could you also add it to https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Extbase/blob/latest/Documentation/Fluid/ViewHelper/Link/Page.rst ?

**Comment by marble** [comment]
Sure. I had done that already. Very good you pay attention and care. Keep on!

**Pull request merged**
