### PR TITLE
Quote fields in select.where etc.

### PR DESCRIPTION
**Pull request by sypets**
Resolves: #354
Releases: master, 10.4, 9.5, 8.7

### CODE REVIEW

**Comment by lolli42** [comment]
good one!

**Comment by lolli42** [comment]
I skipped the 8.7 backport since 8.7 is out of support and the cherry-pick gives a conflict ...

**Comment by sypets** [comment]
ok. I usually only backport up to 9.5 as well.

**Comment by sypets** [comment]
There is also a related PR: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Templating/pull/38

**Pull request merged**
