### PR TITLE
Include Cache property to cObjects

### PR DESCRIPTION
**Pull request by tmotyl**
solves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/237

### CODE REVIEW

**Comment by tmotyl** [comment]
not sure whether the approach I took is ok and how to proceed.
Basically all ContentObjects shoudl get the cache property

**Comment by tmotyl** [comment]
Tested it with local docker rendering chain, looks good

**Comment by DanielSiepmann** [comment]
It is intended not to add the property to all cObjects? E.g. FLUIDTEMPLATE did not receive an update.

**Comment by tmotyl** [comment]
It should be added everywhere, but some content objects have different table structure than others so I couldnt just include the same file.

**Pull request merged**
