### PR TITLE
Update tree.pagelayout for multiple

### PR DESCRIPTION
**Pull request by arunspt**

### CODE REVIEW

**Review by linawolf — COMMENTED** [review]
I think this is a valuable example here

**Comment by linawolf** [comment]
I will take care of the failing tests, they are not related to your PR

**Comment by arunspt** [comment]
Thank you. Looking forward.

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
Thanks for your first contribution to this Official Manual!

**Pull request merged**
