### PR TITLE
[TASK] Document relevance of controllerExtensionName for translations

### PR DESCRIPTION
**Pull request by mbrodala**
Please prettify the change as much as possible, I cannot remember the rest syntax. :-X

### CODE REVIEW

**Comment by marble** [comment]
No problem, just keep on submitting!

**Comment by mbrodala** [comment]
Thanks for merging. :-)

**Comment by marble** [comment]
Sure. Done. Just let me know.

**Comment by mbrodala** [comment]
Thanks. Is there some caching involved on the docs site? I can see the change in [6.2](https://docs.typo3.org/typo3cms/TyposcriptReference/6.2/ContentObjects/Fluidtemplate/#extbase-controllerextensionname) but not in [7.6](https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/ContentObjects/Fluidtemplate/#extbase-controllerextensionname)

**Comment by marble** [comment]
Hhm, for some reason the rendering wasn't triggered for the 7-6. Now it's there. Good you noticed.

**Comment by mbrodala** [comment]
Perfect.

**Pull request merged**
