### PR TITLE
Add MenuProcessor (introduced in v8)

### PR DESCRIPTION
**Pull request by spoonerWeb**

### CODE REVIEW

**Comment by marble** [comment]
Should we backport this one to 8.7?

**Comment by spoonerWeb** [comment]
I thought I edited version 8, so yes.

**Comment by marble** [comment]
Oh you did, sorry, I mistook that.

**Comment by spoonerWeb** [comment]
But you can foreport it to v9. 😄

**Comment by marble** [comment]
Done. Applied to latest.

**Pull request merged**
